function temp = setHamsMedia(model)
components = [{'arginine[e]'}; ...
{'histidine[e]'}; ...
{'lysine[e]'}; ...
{'methionine[e]'}; ...
{'phenylalanine[e]'}; ...
{'tryptophan[e]'}; ...
{'tyrosine[e]'}; ...
{'alanine[e]'}; ...
{'glycine[e]'}; ...
{'serine[e]'}; ...
{'threonine[e]'}; ...
{'aspartate[e]'}; ...
{'glutamate[e]'}; ...
{'asparagine[e]'}; ...
{'glutamine[e]'}; ...
{'isoleucine[e]'}; ...
{'leucine[e]'}; ...
{'proline[e]'}; ...
{'valine[e]'}; ...
{'cysteine[e]'}; ...
{'thiamin[e]'}; ...
{'hypoxanthine[e]'}; ...
{'folate[e]'}; ...
{'biotin[e]'}; ...
{'pantothenate[e]'}; ...
{'choline[e]'}; ...
{'inositol[e]'}; ...
{'nicotinamide[e]'}; ...
{'pyridoxine[e]'}; ...
{'riboflavin[e]'}; ...
{'thymidine[e]'}; ...
{'aquacob(III)alamin[e]'}; ...
{'lipoic acid[e]'}; ...
{'glucose[e]'}; ...
{'sulfate[e]'}; ...
{'linoleate[e]'}; ...
{'linolenate[e]'}; ...
{'O2[e]'}; ...
{'H2O[e]'}; ...
{'retinoate[e]'}; ...
{'Fe2+[e]'}; ...
{'Pi[e]'}; ...
{'alpha-tocopherol[e]'}; ...
{'gamma-tocopherol[e]'}];
[~,expos] = getExchangeRxns(model);
temp = model;
%block all uptakes, allow all secretions
temp.lb(expos) = 0;
temp.ub(expos) = 1000;
%allow unit growth
growthIdx = find(contains(model.rxns,'MAR10024'));
%temp.ub(growthIdx) = 1;
for i = 1:length(components)
    str = strrep(components{i},'[e]','');
    metpos = find(strcmp(model.metNames,str) & model.metComps==1);
    rxnpos = find(model.S(metpos,:));
    rxnpos = intersect(expos,rxnpos);
    %these are reactions of the form met[e] -> {}
    %allow negative flux for uptake
    if strcmpi(str,'O2')
        temp.lb(rxnpos) = -1000;
    elseif strcmpi(str,'glucose')
        temp.lb(rxnpos) = -1;
    else
        temp.lb(rxnpos) = -0.1;
    end
end
temp = setParam(temp,'obj',growthIdx,1);
sol =solveLP(temp,1);
if isempty(sol.x)
    warning('unfeasible solution...Check constraints')
end
end
